### ISSUE TITLE
update ISCAN Tutorial 1 for current interface

### ISSUE THREAD

**Issue by msonderegger** [MontrealCorpusTools/iscan-server#144]
whole ISCAN Tutorial 1 needs to be updated for current ISCAN version, soon.

**don't close this** without also raising an issue that Tutorial 1 needs to -> readthedocs site, but this is less urgent.

@vannawillerton do you have time soon (like next 24 hours). else I'll do.

(addresses #132 )

**Comment by vannawillerton** [comment]
Are we transferring to rtd? I don't quite understand your 'do not close' command?

On wordpress this is done and could be closed.

**Comment by mmcauliffe** [comment]
Transferred to RTD and updated.  Still needs higher res pics, but I'll make a separate issue for that
