### ISSUE TITLE
ISCAN tutorial 2 update

### ISSUE THREAD

**Issue by msonderegger** [MontrealCorpusTools/iscan-server#145]
whole ISCAN Tutorial 2 in WordPress needs to be updated for current ISCAN version, soon.

**don't close this** without also raising an issue that Tutorial 1 needs to -> readthedocs site, but this is less urgent.

@vannawillerton do you have time soon? else I will do.

(addresses #132 )

**Comment by mmcauliffe** [comment]
Tutorial 2 migrated and updated to current version.
