### ISSUE TITLE
Third tutorial (https://polyglot-server.readthedocs.io/en/latest/tutorials_iscan.html) R code

### ISSUE THREAD

**Issue by staceyharkin** [MontrealCorpusTools/iscan-server#153]
Hi,
On the Glasgow University lab computers and my own mac laptop, the tidyverse package isn't installed or seems to have some kind of bug. Dr. Rachel Macdonald was able to install tidyverse, but it still isn't working on my mac. I'm quite new to R, so I just ran the plots using ggplot2 which worked. Would it be possible to use a more basic package or include an alternative? I've included my R Console output below:

R version 3.4.3 (2017-11-30) -- "Kite-Eating Tree"
Copyright (C) 2017 The R Foundation for Statistical Computing
Platform: x86_64-apple-darwin15.6.0 (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> library(tidyverse)
Error in library(tidyverse) : there is no package called ‘tidyverse’
> setwd("~/Documents")
> df <- read.csv('syllable_duration export.csv')
> library("rlang", lib.loc="/Library/Frameworks/R.framework/Versions/3.4/Resources/library")
> df <- filter(df, word_num_syllables < 5)
Error in filter(df, word_num_syllables < 5) : 
  object 'word_num_syllables' not found
> ggplot(df, aes(x = syllable_duration)) +
+   geom_histogram() +
+   xlab("Syllable duration")
Error in ggplot(df, aes(x = syllable_duration)) : 
  could not find function "ggplot"
> library("ggplot2", lib.loc="/Library/Frameworks/R.framework/Versions/3.4/Resources/library")
> ggplot(df, aes(x = syllable_duration)) +
+   geom_histogram() +
+   xlab("Syllable duration")
`stat_bin()` using `bins = 30`. Pick better value with `binwidth`.
> df <- filter(df, syllable_duration < 1.5)
Error in filter(df, syllable_duration < 1.5) : 
  object 'syllable_duration' not found
> ggplot(df, aes(x = factor(word_num_syllables), y = syllable_duration)) +
+   geom_boxplot() +
+   xlab("Duration of word-initial syllable") + ylab("Syllable duration") +
+   scale_y_sqrt()
> install.packages("tidyverse")
Error in install.packages : Updating loaded packages

Restarting R session...

> install.packages("tidyverse")
Error in install.packages : Updating loaded packages
> install.packages("tidyverse")
also installing the dependencies ‘ps’, ‘bindr’, ‘Rcpp’, ‘rematch’, ‘processx’, ‘bindrcpp’, ‘tidyselect’, ‘plogr’, ‘DBI’, ‘curl’, ‘openssl’, ‘cellranger’, ‘callr’, ‘clipr’, ‘fs’, ‘whisker’, ‘selectr’, ‘broom’, ‘dplyr’, ‘dbplyr’, ‘forcats’, ‘haven’, ‘httr’, ‘lubridate’, ‘modelr’, ‘purrr’, ‘readxl’, ‘reprex’, ‘rvest’, ‘tidyr’, ‘xml2’

  There is a binary version available but the source version is later:
      binary source needs_compilation
broom  0.4.5  0.5.0             FALSE

trying URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.4/ps_1.1.0.tgz'
Content type 'application/x-gzip' length 144390 bytes (141 KB)
==================================================
downloaded 141 KB

trying URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.4/bindr_0.1.1.tgz'
Content type 'application/x-gzip' length 12791 bytes (12 KB)
==================================================
downloaded 12 KB

trying URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.4/Rcpp_0.12.19.tgz'
Content type 'application/x-gzip' length 4429794 bytes (4.2 MB)
==================================================
downloaded 4.2 MB

trying URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.4/rematch_1.0.1.tgz'
Content type 'application/x-gzip' length 10990 bytes (10 KB)
==================================================
downloaded 10 KB

trying URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.4/processx_3.2.0.tgz'
Content type 'application/x-gzip' length 106862 bytes (104 KB)
==================================================
downloaded 104 KB

trying URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.4/bindrcpp_0.2.2.tgz'
Content type 'application/x-gzip' length 369636 bytes (360 KB)
==================================================
downloaded 360 KB

trying URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.4/tidyselect_0.2.4.tgz'
Content type 'application/x-gzip' length 292675 bytes (285 KB)
==================================================
downloaded 285 KB

trying URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.4/plogr_0.2.0.tgz'
Content type 'application/x-gzip' length 12957 bytes (12 KB)
==================================================
downloaded 12 KB

trying URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.4/DBI_1.0.0.tgz'
Content type 'application/x-gzip' length 829862 bytes (810 KB)
==================================================
downloaded 810 KB

trying URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.4/curl_3.2.tgz'
Content type 'application/x-gzip' length 404610 bytes (395 KB)
==================================================
downloaded 395 KB

trying URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.4/openssl_1.0.2.tgz'
Content type 'application/x-gzip' length 2418186 bytes (2.3 MB)
==================================================
downloaded 2.3 MB

trying URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.4/cellranger_1.1.0.tgz'
Content type 'application/x-gzip' length 72965 bytes (71 KB)
==================================================
downloaded 71 KB

trying URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.4/callr_3.0.0.tgz'
Content type 'application/x-gzip' length 98436 bytes (96 KB)
==================================================
downloaded 96 KB

trying URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.4/clipr_0.4.1.tgz'
Content type 'application/x-gzip' length 25268 bytes (24 KB)
==================================================
downloaded 24 KB

trying URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.4/fs_1.2.6.tgz'
Content type 'application/x-gzip' length 721951 bytes (705 KB)
==================================================
downloaded 705 KB

trying URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.4/whisker_0.3-2.tgz'
Content type 'application/x-gzip' length 48077 bytes (46 KB)
==================================================
downloaded 46 KB

trying URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.4/selectr_0.4-1.tgz'
Content type 'application/x-gzip' length 101549 bytes (99 KB)
==================================================
downloaded 99 KB

trying URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.4/dplyr_0.7.6.tgz'
Content type 'application/x-gzip' length 5173828 bytes (4.9 MB)
==================================================
downloaded 4.9 MB

trying URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.4/dbplyr_1.2.2.tgz'
Content type 'application/x-gzip' length 318140 bytes (310 KB)
==================================================
downloaded 310 KB

trying URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.4/forcats_0.3.0.tgz'
Content type 'application/x-gzip' length 190427 bytes (185 KB)
==================================================
downloaded 185 KB

trying URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.4/haven_1.1.2.tgz'
Content type 'application/x-gzip' length 885236 bytes (864 KB)
==================================================
downloaded 864 KB

trying URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.4/httr_1.3.1.tgz'
Content type 'application/x-gzip' length 284210 bytes (277 KB)
==================================================
downloaded 277 KB

trying URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.4/lubridate_1.7.4.tgz'
Content type 'application/x-gzip' length 1246139 bytes (1.2 MB)
==================================================
downloaded 1.2 MB

trying URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.4/modelr_0.1.2.tgz'
Content type 'application/x-gzip' length 170974 bytes (166 KB)
==================================================
downloaded 166 KB

trying URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.4/purrr_0.2.5.tgz'
Content type 'application/x-gzip' length 236036 bytes (230 KB)
==================================================
downloaded 230 KB

trying URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.4/readxl_1.1.0.tgz'
Content type 'application/x-gzip' length 1452194 bytes (1.4 MB)
==================================================
downloaded 1.4 MB

trying URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.4/reprex_0.2.1.tgz'
Content type 'application/x-gzip' length 371301 bytes (362 KB)
==================================================
downloaded 362 KB

trying URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.4/rvest_0.3.2.tgz'
Content type 'application/x-gzip' length 852813 bytes (832 KB)
==================================================
downloaded 832 KB

trying URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.4/tidyr_0.8.1.tgz'
Content type 'application/x-gzip' length 584403 bytes (570 KB)
==================================================
downloaded 570 KB

trying URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.4/xml2_1.2.0.tgz'
Content type 'application/x-gzip' length 821238 bytes (801 KB)
==================================================
downloaded 801 KB

trying URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.4/tidyverse_1.2.1.tgz'
Content type 'application/x-gzip' length 77756 bytes (75 KB)
==================================================
downloaded 75 KB

The downloaded binary packages are in
	/var/folders/nc/y514rsk933d86zm90j85mf8r0000gn/T//RtmpsWDnOw/downloaded_packages
installing the source package ‘broom’

trying URL 'https://cran.rstudio.com/src/contrib/broom_0.5.0.tar.gz'
Content type 'application/x-gzip' length 1228314 bytes (1.2 MB)
==================================================
downloaded 1.2 MB

* installing *source* package ‘broom’ ...
** package ‘broom’ successfully unpacked and MD5 sums checked
** R
** data
*** moving datasets to lazyload DB
** inst
** preparing package for lazy loading
** help
*** installing help indices
*** copying figures
** building package indices
** installing vignettes
** testing if installed package can be loaded
* DONE (broom)

The downloaded source packages are in
	‘/private/var/folders/nc/y514rsk933d86zm90j85mf8r0000gn/T/RtmpsWDnOw/downloaded_packages’
> library(tidyverse)
Error: package or namespace load failed for ‘tidyverse’ in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]):
 namespace ‘Rcpp’ 0.12.15 is already loaded, but >= 0.12.16 is required
> df <- filter(df, word_num_syllables < 5)
Error in filter(df, word_num_syllables < 5) : 
  object 'word_num_syllables' not found
> library("tidyverse", lib.loc="/Library/Frameworks/R.framework/Versions/3.4/Resources/library")
Error: package or namespace load failed for ‘tidyverse’ in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]):
 namespace ‘Rcpp’ 0.12.15 is already loaded, but >= 0.12.16 is required
> library(tidyverse)
Error: package or namespace load failed for ‘tidyverse’ in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]):
 namespace ‘Rcpp’ 0.12.15 is already loaded, but >= 0.12.16 is required
>

**Comment by james-tanner** [comment]
Thanks @staceyharkin - I've now updated the tutorial to suggest using ggplot2 if one isn't able to install tidyverse (which I believe is due to a mismatch between tidyverse and the base R version). The tutorial now notes that if the user opts to use ggplot2, they should call the base R `subset()` functions instead of tidyverse's `filter()` at the appropriate steps.
