### ISSUE TITLE
axis labels misaligned and text overlap on 'View Detail' page

### ISSUE THREAD

**Issue by vannawillerton** [MontrealCorpusTools/iscan-server#154]
In the newest version of google chrome AND firefox, there is some overlap of text and the labels for the y axis are off, making it difficult or impossible to read.

![screenshot from 2018-10-11 17-10-01](https://user-images.githubusercontent.com/35343316/46834686-11045180-cd7a-11e8-8c64-ab5687f008a6.png)

**Comment by JaneStuart-Smith** [comment]
Just found this too, this is how it looks on chrome on windows
![detail_view_looks_a_bit_odd_181015_chrome](https://user-images.githubusercontent.com/43891160/46980238-e42ea200-d0cb-11e8-8a77-bb85aaad7c02.PNG)
